### ISSUE TITLE
fullscreen element

### ISSUE THREAD

**Issue by amiad** [amiad/screenshot.js#4]

**Comment by amiad** [comment]
css (maybe inline with JS):
```css
.fullscreen {
	position: fixed;
	top: 0;
	left: 0;
	width: 100vw !important;
	height: 100vh !important;
	z-index: 100000;
}
```

Maybe 2000 ms timeout.
